// ==UserScript==
// @name Nyantube
// @namespace m3tior.github.io
// @description Changes the Youtube progress bar to Nyan Cat.
// @author Ruby Allison Rose (AKA: M3TIOR)
// @homepage https://github.com/m3tior/userscripts
// @include https://www.youtube.com/watch?*
// @run-at document-start
// @version 1.0.7
// ==/UserScript==
!function(){"use-strict";const A={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",decode:e=>{let t,d,n,r,a,i,o,p=[],u=0;for(;u<e.length;)r=A._keyStr.indexOf(e.charAt(u++)),a=A._keyStr.indexOf(e.charAt(u++)),i=A._keyStr.indexOf(e.charAt(u++)),o=A._keyStr.indexOf(e.charAt(u++)),t=r<<2|a>>4,d=(15&a)<<4|i>>2,n=(3&i)<<6|o,p.push(t),64!=i&&p.push(d),64!=o&&p.push(n);return p}},e=new Uint8Array(A.decode("R0lGODlhIQAVAMIGAAAAAP8zmZmZmf+Z///Mmf///6KakaKakSH/C05FVFNDQVBFMi4wAwEAAAAh/hFDcmVhdGVkIHdpdGggR0lNUAAh+QQJAQAHACwAAAAAIQAVAAADnHi6C/4wOkYrIDjrjUH9FzaMZElm3seE5hCMb9mpKwG3+ECk9HHlI8dN55mofjmAQACQOZYpiAJZiimhpytzCi3aksvuMxy9Pr4ukzbMhjbM1Oq63eaNf7GStjDnu98OaGpkWkp3FnFpA0ojdGFBICJ5QQKNZlCVi5EiLYUSfxRnHCiOZCCEEqkSR10+oFxbZjRSPkahRrY9ursKCQAh+QQJAQAHACwAAAAAIQAVAAADnXi6C/4wOkYrIDjrjUH9FzaMZElm3seE5hCMb9mpKwG3+ECk9HHlJIdrtFNMQDYgQCAAnDzLJrIVG0SbRAdT6uP9lNvmIwxlpr5D0zXMLosdSdNrzWYbybZq6Vqg95kNUWgtV1pmYoArcHJBAiN1WyNIeYSOA02HmJIWGTmFEmYgIRwokFs8K2YSq6wqgj6hFK+vrkddqIFntj28vQkAIfkECQEABwAsAAAAACEAFQAAA514utz+0IFJq51Rks2730C2ANxgnujJhSJJpENgyigoHuQM7wPBZjmeaRIz+RSYR5AHEAgAqlDzqXylaIPp0zhxUjXCrPdJGf8YS+xJO26fkUuUjN1ujyov9dpboPedOGxxKVpdTk2GOF4UVidYTSZ1XiZwGC5FhAKRU5yaA1UbTIsXh0ouHyuSixCIF66vEZyKX2ilsqxJgW+VvAcJACH5BAkBAAcALAAAAAAhABUAAAOfeLrc/tCBSaudUZLNu99AtgDcYJ7oyYUiSaRDYMooKB7kDO8DwWY5nmkSM/kUmEeQBxAIAKpQ86l8pWiD6dM4cVI1wqz3SRn/GEvsSTtun3ET61XcrjtH05x67S2wBX53OGZyMFpdTk2Ig2Rxc0MCJnZOJowsLkUpTZJ5iZEDSD8uhSiHF4lKox8gk6gSiRexshB5lq9UtbRJcG+hl7sJACH5BAkBAAcALAAAAAAhABUAAAOeeLrc/tCBSaudUZLNu99AtgDcYJ7oyYUiSaRDYMooKB7kDO8DwWY53mCi64UwkOAOIBAAapPmr6E80ZhSFdapqHRfvK2T0pTiyhVwLCUuu7lRdNXafrtZFeeLhtoW2n9mDBRqbHJoY4JUhWtDAiZ2ZSZTIxuNJ0yQWJuPQxIujJNyFoojhB8rkWgSoxeuFw+bZ1xUZrJJSDi5g0gUDQkAIfkECQEABwAsAAAAACEAFQAAA514utz+0IFJq51Rks2730C2ANxgnujJhSJJpENgyigoHuQMD1NKhBhIbscTCAAx0w9gZGmIxaaK2Rw5hygatUkxVnFfLGzrLYe5k5fuRDabWWTxKbAttO1fHDVHQ20nXkyARw0UamMCJm5eJk4MclqJA0dNlY0PLkkpfxd5jy6Hm4uBmEegHyAXFKVoqq6EQlV7ErKehUGrEkF6jgcJADs=")),t=new Blob([e.buffer],{type:"image/gif"}),d=(URL.createObjectURL(t),".ytp-play-progress { padding: 2.5px 1px; top: -2px; background: linear-gradient( to bottom, #f00 0%, #f90 17%, #ff0 33%, #3f0 50%, #09f 67%, #63f 83%; ); } .ytp-scrubber-container { background: url(${gifURL}) no-repeat; background-size: 36px; width: 40px; height: 24px; margin-top: -4px; } .ytp-scrubber-container:hover { background-size: 40px; margin-top: -6px; margin-left: -2px; } .ytp-scrubber-button { display: none; }");if("undefined"!=typeof GM_addStyle)GM_addStyle(d);else if("undefined"!=typeof PRO_addStyle)PRO_addStyle(d);else if("undefined"!=typeof addStyle)addStyle(d);else{const A=document.createElement("style");A.type="text/css",A.appendChild(document.createTextNode(d));const e=document.getElementsByTagName("head");e.length>0?e[0].appendChild(A):document.documentElement.appendChild(A)}}();
